[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ikob"
version = "0.0.1"
description = "IKOB"
readme = "README.md"
requires-python = ">= 3.8"
dependencies = [
    "openpyxl",
    "xlsxwriter",
]

[tool.setuptools.packages.find]
where = ["ikob/"]

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
ikobrunner = "ikob:main"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
