[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ikob"
version = "0.0.1"
description = "IKOB"
readme = "README.md"
requires-python = ">= 3.8"
dependencies = [
    "numpy",
    "openpyxl",
    "xlsxwriter",
]

[project.optional-dependencies]
dev = [
    "pandas",
    "pytest",
    "ruff",
]

[project.scripts]
ikobrunner = "ikob:ikobrunner.main"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py38"
