# This workflow verifies linting checks

name: linting

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install ikob and dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
    - name: Check source code formatting
      run: |
        autopep8 --aggressive --aggressive --diff --exit-code src/ikob/*.py tests/*.py preprocessing/*.py
    - name: Check import statement formatting
      run: |
        isort --check-only --diff src/ikob/*.py tests/*.py preprocessing/*.py
